# -*- coding: utf-8 -*-
"""Untitled47.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/180hJz5sWCEbjXHVgGXmpfBfq6fwahKwA
"""

import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

"""Introduction to tensors

Creating tensors
"""

# scalar
scalar = torch.tensor(7)
scalar

scalar.ndim

# Get tensor back as Python int
scalar.item()

# Vector
vector = torch.tensor([7, 7])
vector

vector.ndim

vector.shape

# Matrix
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

MATRIX.ndim

MATRIX[1]

MATRIX.shape

# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

TENSOR.ndim

TENSOR.shape

TENSOR[0]